*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 23.02.2019 at 10:01:36
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZCILIB_BOT_V....................................*
TABLES: ZCILIB_BOT_V, *ZCILIB_BOT_V. "view work areas
CONTROLS: TCTRL_ZCILIB_BOT_V
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZCILIB_BOT_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCILIB_BOT_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCILIB_BOT_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_BOT_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_BOT_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCILIB_BOT_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_BOT_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_BOT_V_TOTAL.

*...processing: ZCILIB_HOST_V...................................*
TABLES: ZCILIB_HOST_V, *ZCILIB_HOST_V. "view work areas
CONTROLS: TCTRL_ZCILIB_HOST_V
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZCILIB_HOST_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCILIB_HOST_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCILIB_HOST_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_HOST_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_HOST_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCILIB_HOST_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_HOST_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_HOST_V_TOTAL.

*...processing: ZCILIB_REPO_V...................................*
TABLES: ZCILIB_REPO_V, *ZCILIB_REPO_V. "view work areas
CONTROLS: TCTRL_ZCILIB_REPO_V
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZCILIB_REPO_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCILIB_REPO_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCILIB_REPO_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_REPO_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_REPO_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCILIB_REPO_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_REPO_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_REPO_V_TOTAL.

*...processing: ZCILIB_SETT_V...................................*
TABLES: ZCILIB_SETT_V, *ZCILIB_SETT_V. "view work areas
CONTROLS: TCTRL_ZCILIB_SETT_V
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZCILIB_SETT_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCILIB_SETT_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCILIB_SETT_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_SETT_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_SETT_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCILIB_SETT_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_SETT_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_SETT_V_TOTAL.

*...processing: ZCILIB_SYSGRP_V.................................*
TABLES: ZCILIB_SYSGRP_V, *ZCILIB_SYSGRP_V. "view work areas
CONTROLS: TCTRL_ZCILIB_SYSGRP_V
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZCILIB_SYSGRP_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCILIB_SYSGRP_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCILIB_SYSGRP_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_SYSGRP_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_SYSGRP_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCILIB_SYSGRP_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_SYSGRP_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_SYSGRP_V_TOTAL.

*...processing: ZCILIB_SYSTEM_V.................................*
TABLES: ZCILIB_SYSTEM_V, *ZCILIB_SYSTEM_V. "view work areas
CONTROLS: TCTRL_ZCILIB_SYSTEM_V
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZCILIB_SYSTEM_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZCILIB_SYSTEM_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZCILIB_SYSTEM_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_SYSTEM_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_SYSTEM_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZCILIB_SYSTEM_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZCILIB_SYSTEM_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZCILIB_SYSTEM_V_TOTAL.

*.........table declarations:.................................*
TABLES: ZCILIB_BOT                     .
TABLES: ZCILIB_HOST                    .
TABLES: ZCILIB_REPO                    .
TABLES: ZCILIB_SETTINGS                .
TABLES: ZCILIB_SYSGRP                  .
TABLES: ZCILIB_SYSTEM                  .
